export const statesWithDistricts={
        Chhattisgarh: [ "Durg", "Bastar", "Raipur", "Bilaspur", "Raigarh", "Surguja" ],
        "Madhya Pradesh": [
                "Jabalpur",
                "Balaghat",
                "Chhindwara",
                "Narsinghpur",
                "Seoni / Shivani",
                "Mandla",
                "Sagar",
                "Damoh",
                "Tikamgarh",
                "Chhatarpur",
                "Panna",
                "Rewa",
                "Sidhi",
                "Satna",
                "Shahdol",
                "Gwalior",
                "Shivpuri",
                "Guna",
                "Datia",
                "Morena",
                "Bhind",
                "Indore",
                "Ratlam",
                "Ujjain",
                "Mandsaur",
                "Dewas",
                "Dhar",
                "Jhabua",
                "Khargone / West Nimar",
                "Khandwa / East Nimar",
                "Sehore",
                "Raisen",
                "Vidisha",
                "Betul",
                "Rajgarh",
                "Shajapur",
                "Hoshangabad",
        ],
        "Andhra Pradesh": [
                "Srikakulam",
                "Visakhapatnam",
                "East Godavari",
                "West Godavari",
                "Krishna",
                "Guntur",
                "S.P.S. Nellore",
                "Kurnool",
                "Ananthapur",
                "Kadapa YSR",
                "Chittoor",
        ],
        Telangana: [
                "Hyderabad",
                "Nizamabad",
                "Medak",
                "Mahabubnagar",
                "Nalgonda",
                "Warangal",
                "Khammam",
                "Karimnagar",
                "Adilabad",
        ],
        Karnataka: [
                "Bangalore",
                "Kolar",
                "Tumkur",
                "Mysore",
                "Mandya",
                "Hassan",
                "Shimoge",
                "Chickmagalur",
                "Chitradurga",
                "Bellary",
                "Dharwad",
                "Belgaum",
                "Bijapur / Vijayapura",
                "Bidar",
                "Raichur",
                "Gulbarga / Kalaburagi",
                "Dakshina Kannada",
                "Uttara Kannada",
                "Kodagu / Coorg",
        ],
        "Tamil Nadu": [
                "Chengalpattu MGR / Kanchipuram",
                "South Arcot / Cuddalore",
                "North Arcot / Vellore",
                "Salem",
                "Coimbatore",
                "Tiruchirapalli / Trichy",
                "Thanjavur",
                "Madurai",
                "Ramananthapuram",
                "Thirunelveli",
                "The Nilgiris",
                "Kanyakumari",
        ],
        Maharashtra: [
                "Bombay",
                "Thane",
                "Raigad",
                "Ratnagiri",
                "Nasik",
                "Dhule",
                "Jalgaon",
                "Ahmednagar",
                "Pune",
                "Satara",
                "Sangli",
                "Solapur",
                "Kolhapur",
                "Aurangabad",
                "Parbhani",
                "Beed",
                "Nanded",
                "Osmanabad",
                "Buldhana",
                "Akola",
                "Amarawati",
                "Yeotmal",
                "Wardha",
                "Nagpur",
                "Bhandara",
                "Chandrapur",
        ],
        Gujarat: [
                "Ahmedabad",
                "Amreli",
                "Banaskantha",
                "Bharuch",
                "Vadodara / Baroda",
                "Bhavnagar",
                "Valsad",
                "Dangs",
                "Jamnagar",
                "Junagadh",
                "Kheda",
                "Kutch",
                "Mehsana",
                "Panchmahal",
                "Rajkot",
                "Sabarkantha",
                "Surat",
                "Surendranagar",
        ],
        Rajasthan: [
                "Ajmer",
                "Alwar",
                "Banswara",
                "Barmer",
                "Bharatpur",
                "Bhilwara",
                "Bikaner",
                "Bundi",
                "Chittorgarh",
                "Churu",
                "Dungarpur",
                "Ganganagar",
                "Jaipur",
                "Jaisalmer",
                "Jalore",
                "Jhalawar",
                "Jhunjhunu",
                "Jodhpur",
                "Kota",
                "Nagaur",
                "Pali",
                "Swami Madhopur",
                "Sikar",
                "Sirohi",
                "Tonk",
                "Udaipur",
        ],
        Punjab: [
                "Gurdaspur",
                "Amritsar",
                "Kapurthala",
                "Jalandhar",
                "Hoshiarpur",
                "Roopnagar / Ropar",
                "Ludhiana",
                "Ferozpur",
                "Bhatinda",
                "Sangrur",
                "Patiala",
        ],
        Haryana: [
                "Hissar",
                "Gurgaon",
                "Jind",
                "Mahendragarh / Narnaul",
                "Ambala",
                "Karnal",
                "Rohtak",
        ],
        "Uttar Pradesh": [
                "Saharanpur",
                "Muzaffarnagar",
                "Meerut",
                "Buland Shahar",
                "Aligarh",
                "Mathura",
                "Agra",
                "Mainpuri",
                "Etah",
                "Bareilly",
                "Budaun",
                "Moradabad",
                "Shahjahanpur",
                "Pilibhit",
                "Rampur",
                "Bijnor",
                "Farrukhabad",
                "Etawah",
                "Kanpur",
                "Fatehpur",
                "Allahabad",
                "Jhansi",
                "Jalaun",
                "Hamirpur",
                "Banda",
                "Varanasi",
                "Mirzpur",
                "Jaunpur",
                "Ghazipur",
                "Ballia",
                "Gorakhpur",
                "Deoria",
                "Basti",
                "Azamgarh",
                "Lucknow",
                "Unnao",
                "Rae-Bareily",
                "Sitapur",
                "Hardoi",
                "Kheri",
                "Faizabad",
                "Gonda",
                "Bahraich",
                "Sultanpur",
                "Pratapgarh",
                "Barabanki",
        ],
        Uttarakhand: [
                "Nainital",
                "Almorah",
                "Pithorgarh",
                "Chamoli",
                "Uttar Kashi",
                "Tehri Garhwal",
                "Garhwal",
                "Dehradun",
        ],
        Assam: [
                "Cachar",
                "Darrang",
                "Dibrugarh",
                "Goalpara",
                "Kamrup",
                "Karbi Anglong",
                "Lakhimpur",
                "North Cachar Hil / Dima Hasao",
                "Nagaon",
                "Sibsagar",
        ],
        "Himachal Pradesh": [
                "Bilashpur",
                "Chamba",
                "Kangra",
                "Kinnaur",
                "Kullu",
                "Lahul & Spiti",
                "Solan",
                "Mandi",
                "Shimla",
                "Sirmaur",
        ],
        Kerala: [
                "Alappuzha",
                "Kannur",
                "Eranakulam",
                "Kottayam",
                "Kozhikode",
                "Malappuram",
                "Palakkad",
                "Kollam",
                "Thrissur",
                "Thiruvananthapuram",
        ],
        Orissa: [
                "Balasore",
                "Bolangir",
                "Cuttack",
                "Dhenkanal",
                "Ganjam",
                "Kalahandi",
                "Keonjhar",
                "Koraput",
                "Mayurbhanja",
                "Phulbani (Kandhamal)",
                "Puri",
                "Sambalpur",
                "Sundargarh",
        ],
        "West Bengal": [
                "24 Parganas",
                "Nadia",
                "Murshidabad",
                "Burdwan",
                "Birbhum",
                "Bankura",
                "Hooghly",
                "Howrah",
                "Jalpaiguri",
                "Darjeeling",
                "Malda",
                "Cooch Behar",
                "Purulia",
                "Midnapur",
                "West Dinajpur",
        ],
        Bihar: [
                "Champaran",
                "Muzaffarpur",
                "Darbhanga",
                "Saharsa",
                "Purnea",
                "Saran",
                "Patna",
                "Mungair",
                "Bhagalpur",
                "Santhal Paragana / Dumka",
                "Shahabad (now part of Bhojpur district)",
                "Gaya",
                "Hazaribagh",
                "Dhanbad",
                "Palamau",
                "Ranchi",
                "Singhbhum",
        ],
        Jharkhand: [
                "Champaran",
                "Muzaffarpur",
                "Darbhanga",
                "Saharsa",
                "Purnea",
                "Saran",
                "Patna",
                "Mungair",
                "Bhagalpur",
                "Santhal Paragana / Dumka",
                "Shahabad (now part of Bhojpur district)",
                "Gaya",
                "Hazaribagh",
                "Dhanbad",
                "Palamau",
                "Ranchi",
                "Singhbhum",
        ],
};

export const cropProductionOptions=[
        "RICE AREA (1000 ha)",
        "RICE PRODUCTION (1000 tons)",
        "RICE YIELD (Kg per ha)",
        "WHEAT AREA (1000 ha)",
        "WHEAT PRODUCTION (1000 tons)",
        "WHEAT YIELD (Kg per ha)",
        "KHARIF SORGHUM AREA (1000 ha)",
        "KHARIF SORGHUM PRODUCTION (1000 tons)",
        "KHARIF SORGHUM YIELD (Kg per ha)",
        "RABI SORGHUM AREA (1000 ha)",
        "RABI SORGHUM PRODUCTION (1000 tons)",
        "RABI SORGHUM YIELD (Kg per ha)",
        "COTTON AREA (1000 ha)",
        "COTTON PRODUCTION (1000 tons)",
        "COTTON YIELD (Kg per ha)",
        "SUGAR CANE AREA (1000 ha)",
        "SUGAR CANE PRODUCTION (1000 tons)",
        "SUGAR CANE YIELD (Kg per ha)",
        "POTATO AREA (1000 ha)",
        "POTATO PRODUCTION (1000 tons)",
        "POTATO YIELD (Kg per ha)",
        "ONION AREA (1000 ha)",
        "ONION PRODUCTION (1000 tons)",
        "ONION YIELD (Kg per ha)",
        "GROUNDNUT AREA (1000 ha)",
        "GROUNDNUT PRODUCTION (1000 tons)",
        "GROUNDNUT YIELD (Kg per ha)",
];

export const cropPriceOptions=[
        "RICE HARVEST PRICE (Rs per Quintal)",
        "PADDY HARVEST PRICE (Rs per Quintal)",
        "WHEAT HARVEST PRICE (Rs per Quintal)",
        "SORGHUM HARVEST PRICE (Rs per Quintal)",
        "PEARL MILLET HARVEST PRICE (Rs per Quintal)",
        "MAIZE HARVEST PRICE (Rs per Quintal)",
        "FINGER MILLET HARVEST PRICE (Rs per Quintal)",
        "BARLEY HARVEST PRICE (Rs per Quintal)",
        "CHICKPEA HARVEST PRICE (Rs per Quintal)",
        "PIGEONPEA HARVEST PRICE (Rs per Quintal)",
        "GROUNDNUT HARVEST PRICE (Rs per Quintal)",
        "SEASMUM HARVEST PRICE (Rs per Quintal)",
        "RAPE AND MUSTARD HARVEST PRICE (Rs per Quintal)",
        "CASTOR HARVEST PRICE (Rs per Quintal)",
        "LINSEED HARVEST PRICE (Rs per Quintal)",
        "SUGARCANE GUR HARVEST PRICE (Rs per Quintal)",
        "COTTON KAPAS HARVEST PRICE (Rs per Quintal)",
];